### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by aussiegeek** [aussiegeek/ruby-sass-tmbundle#4]
I no longer use TextMate, so it probably makes sense for someone else to takeover the fork.

I'm all ears as to who

**Comment by activestylus** [comment]
I would totally do it if I had the slightest idea how.

What did you end up switching to, out of curiosity? emacs? vim?

**Comment by aussiegeek** [comment]
I switched to Vim, split screen, hasn't ever crashed. I do miss textmate's indent handling

**Comment by adamstac** [comment]
I'm in the process of revamping my Haml and Sass TextMate bundles. I'd be happy to take over for you.

Shoot me an email adam@gethandcrafted.com, IM me at adamstac@mac.com or hit me up on Twitter http://twitter.com/adamstac.

**Comment by aussiegeek** [comment]
It's now official, adamstac has taken over dev of this bundle. Thanks for the help Adam!

**Comment by elia** [comment]
Alan take a look at [@cehoffman fork](http://github.com/cehoffman/ruby-sass-tmbundle), he seems the most active forker, perhaps you should give him push privileges to your sass bundle repo
